// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "booking-service/internal/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GuestServiceMock is an autogenerated mock type for the GuestService type
type GuestServiceMock struct {
	mock.Mock
}

// CreateGuest provides a mock function with given fields: ctx, _a1
func (_m *GuestServiceMock) CreateGuest(ctx context.Context, _a1 entities.GuestDTO) (entities.Guest, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateGuest")
	}

	var r0 entities.Guest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.GuestDTO) (entities.Guest, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.GuestDTO) entities.Guest); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(entities.Guest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.GuestDTO) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindGuestsByBookingID provides a mock function with given fields: ctx, bookingID
func (_m *GuestServiceMock) FindGuestsByBookingID(ctx context.Context, bookingID uint) ([]entities.Guest, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindGuestsByBookingID")
	}

	var r0 []entities.Guest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entities.Guest, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.Guest); ok {
		r0 = rf(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Guest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGuestServiceMock creates a new instance of GuestServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGuestServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GuestServiceMock {
	mock := &GuestServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
