// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "booking-service/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// RoomRepoMock is an autogenerated mock type for the RoomRepo type
type RoomRepoMock struct {
	mock.Mock
}

// FindById provides a mock function with given fields: ctx, roomId
func (_m *RoomRepoMock) FindById(ctx context.Context, roomId int64) (*entities.Room, error) {
	ret := _m.Called(ctx, roomId)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entities.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Room, error)); ok {
		return rf(ctx, roomId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Room); ok {
		r0 = rf(ctx, roomId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, roomId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *RoomRepoMock) Save(ctx context.Context, _a1 *entities.Room) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Room) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveAll provides a mock function with given fields: ctx, rooms
func (_m *RoomRepoMock) SaveAll(ctx context.Context, rooms []entities.Room) error {
	ret := _m.Called(ctx, rooms)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entities.Room) error); ok {
		r0 = rf(ctx, rooms)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *RoomRepoMock) Update(ctx context.Context, _a1 *entities.Room) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Room) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoomRepoMock creates a new instance of RoomRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomRepoMock {
	mock := &RoomRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
