// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "booking-service/internal/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HouseKeepingRequestServiceMock is an autogenerated mock type for the HouseKeepingRequestService type
type HouseKeepingRequestServiceMock struct {
	mock.Mock
}

// AssignEmployee provides a mock function with given fields: ctx, requestID, EmployeeID
func (_m *HouseKeepingRequestServiceMock) AssignEmployee(ctx context.Context, requestID uint64, EmployeeID uint64) (entities.HousekeepingRequest, error) {
	ret := _m.Called(ctx, requestID, EmployeeID)

	if len(ret) == 0 {
		panic("no return value specified for AssignEmployee")
	}

	var r0 entities.HousekeepingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) (entities.HousekeepingRequest, error)); ok {
		return rf(ctx, requestID, EmployeeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) entities.HousekeepingRequest); ok {
		r0 = rf(ctx, requestID, EmployeeID)
	} else {
		r0 = ret.Get(0).(entities.HousekeepingRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, requestID, EmployeeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateHouseKeepingRequest provides a mock function with given fields: ctx, request
func (_m *HouseKeepingRequestServiceMock) CreateHouseKeepingRequest(ctx context.Context, request entities.HouseKeepingRequestDTO) (entities.HousekeepingRequest, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateHouseKeepingRequest")
	}

	var r0 entities.HousekeepingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.HouseKeepingRequestDTO) (entities.HousekeepingRequest, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.HouseKeepingRequestDTO) entities.HousekeepingRequest); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(entities.HousekeepingRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.HouseKeepingRequestDTO) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHouseKeepingRequestServiceMock creates a new instance of HouseKeepingRequestServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHouseKeepingRequestServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HouseKeepingRequestServiceMock {
	mock := &HouseKeepingRequestServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
