// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	generated "booking-service/internal/generated"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ClientMock is an autogenerated mock type for the client type
type ClientMock struct {
	mock.Mock
}

// CancelPayment provides a mock function with given fields: ctx, in, opts
func (_m *ClientMock) CancelPayment(ctx context.Context, in *generated.BookingInfo, opts ...grpc.CallOption) (*generated.ProcessResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CancelPayment")
	}

	var r0 *generated.ProcessResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *generated.BookingInfo, ...grpc.CallOption) (*generated.ProcessResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *generated.BookingInfo, ...grpc.CallOption) *generated.ProcessResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.ProcessResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *generated.BookingInfo, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentsInfo provides a mock function with given fields: ctx, in, opts
func (_m *ClientMock) GetPaymentsInfo(ctx context.Context, in *generated.BookingInfo, opts ...grpc.CallOption) (*generated.PaymentsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentsInfo")
	}

	var r0 *generated.PaymentsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *generated.BookingInfo, ...grpc.CallOption) (*generated.PaymentsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *generated.BookingInfo, ...grpc.CallOption) *generated.PaymentsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.PaymentsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *generated.BookingInfo, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessPayment provides a mock function with given fields: ctx, in, opts
func (_m *ClientMock) ProcessPayment(ctx context.Context, in *generated.ProcessRequest, opts ...grpc.CallOption) (*generated.ProcessResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 *generated.ProcessResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *generated.ProcessRequest, ...grpc.CallOption) (*generated.ProcessResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *generated.ProcessRequest, ...grpc.CallOption) *generated.ProcessResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.ProcessResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *generated.ProcessRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientMock creates a new instance of ClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
