// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "booking-service/internal/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReviewServiceMock is an autogenerated mock type for the ReviewService type
type ReviewServiceMock struct {
	mock.Mock
}

// SubmitReview provides a mock function with given fields: ctx, reviewDTO
func (_m *ReviewServiceMock) SubmitReview(ctx context.Context, reviewDTO entities.ReviewDTO) (entities.Review, error) {
	ret := _m.Called(ctx, reviewDTO)

	if len(ret) == 0 {
		panic("no return value specified for SubmitReview")
	}

	var r0 entities.Review
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.ReviewDTO) (entities.Review, error)); ok {
		return rf(ctx, reviewDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.ReviewDTO) entities.Review); ok {
		r0 = rf(ctx, reviewDTO)
	} else {
		r0 = ret.Get(0).(entities.Review)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.ReviewDTO) error); ok {
		r1 = rf(ctx, reviewDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReviewServiceMock creates a new instance of ReviewServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewServiceMock {
	mock := &ReviewServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
