// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "booking-service/internal/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// BookingServiceMock is an autogenerated mock type for the BookingService type
type BookingServiceMock struct {
	mock.Mock
}

// CancelBooking provides a mock function with given fields: ctx, bookingID
func (_m *BookingServiceMock) CancelBooking(ctx context.Context, bookingID uint64) error {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBooking provides a mock function with given fields: ctx, input
func (_m *BookingServiceMock) CreateBooking(ctx context.Context, input entities.CreateBookingDTO) (entities.Booking, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateBookingDTO) (entities.Booking, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.CreateBookingDTO) entities.Booking); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(entities.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.CreateBookingDTO) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModifyBooking provides a mock function with given fields: ctx, bookingID, startDate, endDate
func (_m *BookingServiceMock) ModifyBooking(ctx context.Context, bookingID uint64, startDate time.Time, endDate time.Time) (entities.Booking, error) {
	ret := _m.Called(ctx, bookingID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for ModifyBooking")
	}

	var r0 entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) (entities.Booking, error)); ok {
		return rf(ctx, bookingID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) entities.Booking); ok {
		r0 = rf(ctx, bookingID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(entities.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, time.Time, time.Time) error); ok {
		r1 = rf(ctx, bookingID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookingServiceMock creates a new instance of BookingServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingServiceMock {
	mock := &BookingServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
