// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "booking-service/internal/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RoomServiceMock is an autogenerated mock type for the RoomService type
type RoomServiceMock struct {
	mock.Mock
}

// CreateRooms provides a mock function with given fields: ctx, rooms
func (_m *RoomServiceMock) CreateRooms(ctx context.Context, rooms []entities.RoomDTO) error {
	ret := _m.Called(ctx, rooms)

	if len(ret) == 0 {
		panic("no return value specified for CreateRooms")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entities.RoomDTO) error); ok {
		r0 = rf(ctx, rooms)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *RoomServiceMock) Update(ctx context.Context, _a1 entities.RoomDTO) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.RoomDTO) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoomServiceMock creates a new instance of RoomServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomServiceMock {
	mock := &RoomServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
