// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "booking-service/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// ReviewRepoMock is an autogenerated mock type for the ReviewRepo type
type ReviewRepoMock struct {
	mock.Mock
}

// FindByGuest provides a mock function with given fields: ctx, guestID
func (_m *ReviewRepoMock) FindByGuest(ctx context.Context, guestID uint64) ([]entities.Review, error) {
	ret := _m.Called(ctx, guestID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGuest")
	}

	var r0 []entities.Review
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]entities.Review, error)); ok {
		return rf(ctx, guestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []entities.Review); ok {
		r0 = rf(ctx, guestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, guestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *ReviewRepoMock) Save(ctx context.Context, _a1 *entities.Review) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Review) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReviewRepoMock creates a new instance of ReviewRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewRepoMock {
	mock := &ReviewRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
