// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	generated "booking-service/internal/generated"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ClientMock is an autogenerated mock type for the client type
type ClientMock struct {
	mock.Mock
}

// SendNotification provides a mock function with given fields: ctx, in, opts
func (_m *ClientMock) SendNotification(ctx context.Context, in *generated.NotificationDTO, opts ...grpc.CallOption) (*generated.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendNotification")
	}

	var r0 *generated.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *generated.NotificationDTO, ...grpc.CallOption) (*generated.Response, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *generated.NotificationDTO, ...grpc.CallOption) *generated.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *generated.NotificationDTO, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientMock creates a new instance of ClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
