// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "booking-service/internal/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// BookingRepoMock is an autogenerated mock type for the BookingRepo type
type BookingRepoMock struct {
	mock.Mock
}

// CanReschedule provides a mock function with given fields: ctx, bookingID, newStartDate, newEndDate
func (_m *BookingRepoMock) CanReschedule(ctx context.Context, bookingID uint64, newStartDate time.Time, newEndDate time.Time) (bool, error) {
	ret := _m.Called(ctx, bookingID, newStartDate, newEndDate)

	if len(ret) == 0 {
		panic("no return value specified for CanReschedule")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) (bool, error)); ok {
		return rf(ctx, bookingID, newStartDate, newEndDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) bool); ok {
		r0 = rf(ctx, bookingID, newStartDate, newEndDate)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, time.Time, time.Time) error); ok {
		r1 = rf(ctx, bookingID, newStartDate, newEndDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, bookingID
func (_m *BookingRepoMock) Delete(ctx context.Context, bookingID uint64) error {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByDate provides a mock function with given fields: ctx, date
func (_m *BookingRepoMock) FindByDate(ctx context.Context, date time.Time) ([]entities.Booking, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for FindByDate")
	}

	var r0 []entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]entities.Booking, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []entities.Booking); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, bookingID
func (_m *BookingRepoMock) FindById(ctx context.Context, bookingID uint64) (*entities.Booking, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*entities.Booking, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *entities.Booking); ok {
		r0 = rf(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByRoomID provides a mock function with given fields: ctx, roomID
func (_m *BookingRepoMock) FindByRoomID(ctx context.Context, roomID uint64) ([]entities.Booking, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoomID")
	}

	var r0 []entities.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]entities.Booking, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []entities.Booking); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsRoomAvailable provides a mock function with given fields: ctx, roomID, startDate, endDate
func (_m *BookingRepoMock) IsRoomAvailable(ctx context.Context, roomID uint64, startDate time.Time, endDate time.Time) (bool, error) {
	ret := _m.Called(ctx, roomID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for IsRoomAvailable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) (bool, error)); ok {
		return rf(ctx, roomID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, time.Time, time.Time) bool); ok {
		r0 = rf(ctx, roomID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, time.Time, time.Time) error); ok {
		r1 = rf(ctx, roomID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *BookingRepoMock) Save(ctx context.Context, _a1 *entities.Booking) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Booking) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *BookingRepoMock) Update(ctx context.Context, _a1 *entities.Booking) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Booking) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookingRepoMock creates a new instance of BookingRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingRepoMock {
	mock := &BookingRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
