// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "booking-service/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// EmployeeServiceMock is an autogenerated mock type for the EmployeeService type
type EmployeeServiceMock struct {
	mock.Mock
}

// AddEmployee provides a mock function with given fields: ctx, _a1
func (_m *EmployeeServiceMock) AddEmployee(ctx context.Context, _a1 entities.EmployeeDTO) (entities.Employee, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddEmployee")
	}

	var r0 entities.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.EmployeeDTO) (entities.Employee, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.EmployeeDTO) entities.Employee); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(entities.Employee)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.EmployeeDTO) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmployee provides a mock function with given fields: ctx, employeeID
func (_m *EmployeeServiceMock) GetEmployee(ctx context.Context, employeeID uint64) (entities.Employee, error) {
	ret := _m.Called(ctx, employeeID)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployee")
	}

	var r0 entities.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (entities.Employee, error)); ok {
		return rf(ctx, employeeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) entities.Employee); ok {
		r0 = rf(ctx, employeeID)
	} else {
		r0 = ret.Get(0).(entities.Employee)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, employeeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEmployee provides a mock function with given fields: ctx, employeeID, _a2
func (_m *EmployeeServiceMock) UpdateEmployee(ctx context.Context, employeeID uint64, _a2 entities.EmployeeDTO) (entities.Employee, error) {
	ret := _m.Called(ctx, employeeID, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmployee")
	}

	var r0 entities.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, entities.EmployeeDTO) (entities.Employee, error)); ok {
		return rf(ctx, employeeID, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, entities.EmployeeDTO) entities.Employee); ok {
		r0 = rf(ctx, employeeID, _a2)
	} else {
		r0 = ret.Get(0).(entities.Employee)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, entities.EmployeeDTO) error); ok {
		r1 = rf(ctx, employeeID, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEmployeeServiceMock creates a new instance of EmployeeServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmployeeServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmployeeServiceMock {
	mock := &EmployeeServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
