// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "booking-service/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// EmployeeRepositoryMock is an autogenerated mock type for the EmployeeRepository type
type EmployeeRepositoryMock struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, _a1
func (_m *EmployeeRepositoryMock) FindByID(ctx context.Context, _a1 uint64) (entities.Employee, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entities.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (entities.Employee, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) entities.Employee); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(entities.Employee)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *EmployeeRepositoryMock) Save(ctx context.Context, _a1 *entities.Employee) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Employee) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *EmployeeRepositoryMock) Update(ctx context.Context, _a1 *entities.Employee) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Employee) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmployeeRepositoryMock creates a new instance of EmployeeRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmployeeRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmployeeRepositoryMock {
	mock := &EmployeeRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
