// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "booking-service/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// HouseKeepingRequestRepoMock is an autogenerated mock type for the HouseKeepingRequestRepo type
type HouseKeepingRequestRepoMock struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, requestId
func (_m *HouseKeepingRequestRepoMock) FindByID(ctx context.Context, requestId uint64) (*entities.HousekeepingRequest, error) {
	ret := _m.Called(ctx, requestId)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.HousekeepingRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*entities.HousekeepingRequest, error)); ok {
		return rf(ctx, requestId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *entities.HousekeepingRequest); ok {
		r0 = rf(ctx, requestId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.HousekeepingRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, requestId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, request
func (_m *HouseKeepingRequestRepoMock) Save(ctx context.Context, request *entities.HousekeepingRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.HousekeepingRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, request
func (_m *HouseKeepingRequestRepoMock) Update(ctx context.Context, request entities.HousekeepingRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.HousekeepingRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHouseKeepingRequestRepoMock creates a new instance of HouseKeepingRequestRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHouseKeepingRequestRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HouseKeepingRequestRepoMock {
	mock := &HouseKeepingRequestRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
